### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by aaowens** [aaowens/PSID.jl#22]
1. Test more, increasing code coverage. Might need to generate some fake data.
2. Change the Dict key type to String so I can update JSON3

**Comment by aaowens** [comment]
It also would be nice to be able to pull information directly from the individual file. There is some useful information in there, like education (missing in some years in the family files), and the individual sampling weights.

**Comment by eirikbrandsaas** [comment]
Here are some more suggestions, features that would be nice to include:

- [ ] Include support for supplementary files
    - [ ] Wealth Files
- [ ] Speed up the reading of the .txt files
- [ ] Allow for only using a subset for years. For example, limit the sample to the period (1999-) became biennial. (This also would speed up the reading of the text files)

**Comment by aaowens** [comment]
Ya, I think using the supplementary files would require adding an extra field to the input.json file to indicate which files (family, individual, wealth, other?) to look in, and then some code to use that.
